name: aws_lambda_deploy
on: [push]
  # release:
  #   types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to AWS
      uses: appleboy/lambda-action@v0.0.8
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda_jersey_test_1
          zip_file: target/lambda_jersey_test_1-1.0-SNAPSHOT.jar # TODO
          handler: com.lindronics.StreamLambdaHandler
          runtime: java11
